Service:
  name: "Travel on Chain"
  port: ":8080"
LogConfig:
  mode: 1
EthAddress:
  url: ""
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "mysql"
  dbname: "test"

Redis: