server:
  name: "Travel on Chain"
  port: ":8080"   # 服务监听端口号
logConfig:
  mode: 0     # 0 直接输出到标准输出  1 输出到文件
eth:
  apiKeyUrl: "0x123456"
  contractUrl: "0x123456"
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "mysql"
  dbname: "test"

Redis: